image: golang:latest
stages:
        - test

build-market:
        stage: test
        script:
                - mkdir -p $GOPATH/src/gitlab.com/fharding/brainf
                - cp -r . $GOPATH/src/gitlab.com/fharding/brainf/
                - cd $GOPATH/src/gitlab.com/fharding/brainf
                - go test ./...
